FROM ubuntu:focal

RUN apt update
RUN apt install -y zip
RUN apt install -y php-cli
RUN apt install -y git
RUN apt install -y curl

ENV NEXTCLOUD_USER=user
ENV NEXTCLOUD_PASSWORD=pass
ENV NEXTCLOUD_HOST=host
ENV GITHUB_TOKEN=token

WORKDIR /root
COPY ./sourceguardian-entrypoint.sh ./sourceguardian-entrypoint.sh

CMD ./sourceguardian-entrypoint.sh
