version: "3"

services:
  web_ui:
    container_name: web_ui
    build:
      context: web_ui
      dockerfile: Dockerfile
      args:
        - NEXTCLOUD_USER=$NEXTCLOUD_USER
        - NEXTCLOUD_PASSWORD=$NEXTCLOUD_PASSWORD
        - NEXTCLOUD_HOST=$NEXTCLOUD_HOST

#  deprecated service use web_ui instead
  xircl_react:
    container_name: xircl_react
    build:
      context: xircl
      dockerfile: Dockerfile-react
      args:
        - NEXTCLOUD_USER=$NEXTCLOUD_USER
        - NEXTCLOUD_PASSWORD=$NEXTCLOUD_PASSWORD
        - NEXTCLOUD_HOST=$NEXTCLOUD_HOST

#  deprecated service use sourceguardian instead
  sourceguardian_legacy:
    container_name: xircl_sourceguardian
    build:
      context: .
      dockerfile: Dockerfile-sourceguardian
    working_dir: /root
    volumes:
      - ./sourceguardian:/root/sourceguardian
      - /var/run/docker.sock:/var/run/sourceguardian-docker.sock
      - ./xircl:/xircl
    environment:
      NEXTCLOUD_USER: ${NEXTCLOUD_USER}
      NEXTCLOUD_PASSWORD: ${NEXTCLOUD_PASSWORD}
      NEXTCLOUD_HOST: ${NEXTCLOUD_HOST}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

  sourceguardian:
    container_name: xircl_sourceguardian
    build:
      context: .
      dockerfile: Dockerfile-sourceguardian
    working_dir: /root
    volumes:
      - ./sourceguardian:/root/sourceguardian
      - /var/run/docker.sock:/var/run/sourceguardian-docker.sock
      - ./xircl-api:/xircl
    environment:
      NEXTCLOUD_USER: ${NEXTCLOUD_USER}
      NEXTCLOUD_PASSWORD: ${NEXTCLOUD_PASSWORD}
      NEXTCLOUD_HOST: ${NEXTCLOUD_HOST}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
